version: "2.4"

services:
    app:
        build: .
        container_name: app.rms
        environment:
          - PORT=8080
          - DATABASE_URL=postgres://testuser:1234@db.rms:5432/project6?sslmode=disable
        ports:
          - "8080:8080"
        depends_on: 
          - migrations

    migrations:
        build:
            context: .
            dockerfile: Dockerfile.migrations
        container_name: app.rms.migrations
        environment:
          - PORT=8081
          - DATABASE_URL=postgres://testuser:1234@db.rms:5432/project6?sslmode=disable
        ports:
          - "8081:8081"
        depends_on: 
          - db
        volumes:
          - ./pgdata:/var/lib/postgresql/data

    db:
        image: "postgres:13"
        container_name: db.rms
        command: postgres -c 'max_connections=1024'
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=1234
          - POSTGRES_DB=project6
        volumes:
          - ./pgdata:/var/lib/postgresql/data


networks:
  default:
    name: rms-stack