version: "3.8"

services:
    app:
        build: .
        container_name: app.rms
        depends_on: 
          - db
          - migrations
        environment:
          - PORT=8080
          - DATABASE_URL=postgres://testuser:1234@db.rms:5432/project6?sslmode=disable
        ports:
          - "8080:8000"

    migrations:
        build:
            context: .
            dockerfile: Dockerfile.migrations
        container_name: app.rms.migrations
        environment:
          - PORT=8080
          - DATABASE_URL=postgres://testuser:1234@db.rms:5432/project6?sslmode=disable
        command:
          - /app/create_db.sh
        depends_on: 
          - db
        volumes:
          - ./pgdata:/var/lib/postgresql/data

    db:
        image: "postgres:13"
        container_name: db.rms
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=1234
          - POSTGRES_DB=project6
        volumes:
          - ./pgdata:/var/lib/postgresql/data


networks:
  default:
    name: rms-stack