FROM rust as builder
COPY . /app
WORKDIR /app
ENV SQLX_OFFLINE true
RUN cargo build --release


FROM gcr.io/distroless/cc
COPY --from=builder /app/target/release/migrate /app/migrate
WORKDIR /app
ENV SQLX_OFFLINE true
EXPOSE 8081
CMD ["./migrate"]
