version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=project6

# version: '3.8'
# services:
#     web:
#         build: .
#         ports:
#             - "8080:8000"
#         env_file:
#             - .env
#         command: ["/app/rust-actix-realworld-app"]

#     migrations:
#         build:
#             context: .
#             dockerfile: Dockerfile.migrations
#         depends_on:
#             - database
#         env_file:
#             - .env.prod
#         command: ["./wait-for-postgres.sh"]

#     database:
#         image: postgres
#         environment:
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=postgres
#             - POSTGRES_DB=actix_realworld
#         volumes:
#             - ar-pgdata:/var/lib/postgresql/data

# volumes:
#     ar-pgdata:
